{
    "name": "Random String",
    "version": "14.0.1.0.0",
    "category": "Random",
    "author": "Shahil Chauhan",
    "summary": "Random String management system",
    "sequence": 1,
    "website": "https://www.aktivesoftware.com/",
    "description": "Showing button in product and product variant,that generate random string",
    "depends": ["sale_management"],
    "data": ["views/product_views.xml"],
    "demo": [],
    "installable": True,
    "application": True,
    "auto_install": False,
}
