{
    "name": "user error",
    "author": "Yash Shah",
    "summary": "Track order ",
    "description": "This application is helpful to track all records and help you to do proper analyses.",
    "website": "https://www.track order.com/referral/application",
    "category": "Business",
    "version": "14.0.1.0.0",
    "depends": ["sale_management"],
    "data": [],
    "application": True,
    "auto_install": False,
    "installable": True,
    "sequence": "1",
}
